<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo server_url(base_url()) . '/'; ?>" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->renderSection('title', 'Начало'); ?></title>
    <?php echo $this->renderSection('styles'); ?>
</head>
<body role="document">
    <?php echo $this->renderSection('content'); ?>
    <?php echo $this->renderSection('scripts'); ?>
</body>
</html>