<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Превключване</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php
                foreach ($this->widget('Navigation')->navigation('main') as $page) {
                    echo $this->partial('layouts/admin/includes/_item', array('item' => $page, 'level' => 0));
                }
                ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php
                foreach ($this->widget('Navigation')->navigation('right') as $page) {
                    echo $this->partial('layouts/admin/includes/_item', array('item' => $page, 'level' => 0));
                }
                ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>