<!doctype html>
<html lang="en">
<head>
    <base href="<?php echo server_url(base_url()) . '/'; ?>" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="assets/templates/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <style>
    body {
      padding-top: 40px;
      padding-bottom: 40px;

    }
    .form-signin {
      max-width: 330px;
      padding: 15px;
      margin: 0 auto;
    }
    .form-signin .form-control {
      position: relative;
      height: auto;
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
      padding: 10px;
      font-size: 16px;
    }
    .form-signin .form-control:focus {
      z-index: 2;
    }
    .form-signin input[type="text"],
    .form-signin input[type="password"] {
      margin-bottom: 0px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
    .element-error {
    	color: #a94442;
    	margin-top: 2px;
    	margin-bottom: 0px;
    	width: 100%;
    	display: block;
    }
    </style>
    <?php echo $this->renderSection('styles'); ?>
</head>
<body>
    <div class="container">
        <?php echo $this->renderSection('content'); ?>
    </div>
    <?php echo $this->renderSection('scripts'); ?>
</body>
</html>