<?php

if (!function_exists('pp')) {
    function pp($arr) {
        $retStr = '<ul>';
        if (is_array($arr)){
            foreach ($arr as $key => $val){
                if (is_array($val)){
                    $retStr .= '<li>' . $key . ' => ' . pp($val) . '</li>';
                } else if (is_object($val)) {
                    $retStr .= '<li>' . $key . ' => ' . gettype($val) . '</li>';
                } else {
                    $retStr .= '<li>' . $key . ' => ' . $val . '</li>';
                }
            }
        }
        $retStr .= '</ul>';
        return $retStr;
    }
}

$total = microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'];

echo '<div class="debug-bar">';

echo '<div class="debug-item empty">';
printf("<h1>Time: %ss.</h1>", $total);
echo '</div>';

echo '<div class="debug-item">';
echo '<h1>Request</h1>';
echo '<pre>';
try {
    $params = app('request')->getParams();
    if (isset($params['exception']) && $params['exception'] instanceof \Exception) {
        $params['exception'] = $params['exception']->getMessage();
    }
    echo pp($params);
} catch (\Exception $e) {
    echo $e->getMessage();
}
echo '</pre>';
echo '</div>';

try {
    $db = app('db');
} catch (\Exception $e) {
    $db = null;
}

if ($db && $db->getProfiler() && $db->getProfiler()->getEnabled()) {

    $profiler     = $db->getProfiler();
    $totalTime    = $profiler->getTotalElapsedSecs();
    $queryCount   = $profiler->getTotalNumQueries();
    $longestTime  = 0;
    $longestQuery = null;
    $queries      = array();

    echo '<div class="debug-item">';
    echo '<h1>Database (' . $queryCount . ' / ' . sprintf('%.6f', $totalTime) . 's.)</h1>';
    echo '<pre>';
    if ($profiler->getQueryProfiles()) {
        foreach ($profiler->getQueryProfiles() as $query) {
            if ($query->getElapsedSecs() > $longestTime) {
                $longestTime  = $query->getElapsedSecs();
                $longestQuery = $query->getQuery();
            }
            $queries[] = '<div class="debug-query">' . $query->getQuery() . '</div>';
        }
    }
    echo 'Executed ' . $queryCount . ' queries in ' . sprintf('%.6f', $totalTime) . ' seconds' . "<br />";
    if ($profiler->getQueryProfiles()) {
        echo 'Queries percent: ' . ($total ? round(($totalTime / $total) * 100, 2) : 0) . ' %<br/>';
        echo 'Queries:<br />';
        echo implode('', $queries);
        echo 'Average query length: ' . sprintf('%.6f', ($queryCount ? $totalTime / $queryCount : 0)) . ' seconds' . "<br />";
        echo 'Queries per second: ' . sprintf('%.6f', $totalTime ? ($queryCount / $totalTime) : 0) . " seconds<br />";
        echo 'Longest query length: ' . sprintf('%.6f', $longestTime) . " seconds<br />";
        echo "Longest query:<br />";
        echo '<div class="debug-query">' . $longestQuery . '</div>';
    }
    echo '</pre>';
    echo '</div>';
}

echo '<div class="debug-item">';
echo '<h1>Memory</h1>';
echo '<pre>';
echo 'Usage: ' . number_format((memory_get_usage() / 1024 / 1024), 6) . ' MB';
echo '<br />Peak usage: ' . number_format((memory_get_peak_usage() / 1024 / 1024), 6) . ' MB';
echo '</pre>';
echo '</div>';

if (isset($_SESSION)) {
    echo '<div class="debug-item">';
    echo '<h1>Session</h1>';
    echo '<pre>';
    echo pp($_SESSION);
    echo '</pre>';
    echo '</div>';
}

echo '<div class="debug-item">';
echo '<h1>Config</h1>';
echo '<pre>';
echo pp(config());
echo '</pre>';
echo '</div>';

$f  = \MicroLoader::getFiles();
$fn = count($f);

$n  = count(array_filter($f, function ($v) {
    return $v != 'NOT EXISTS';
}));

$an = count(\MicroLoader::getAutoloaded());

echo '<div class="debug-item">';
echo '<h1>Classes (' . ($n - $an) . ' mapped / ' . $fn . ' total)</h1>';
echo '<pre>';
echo $fn;
echo '<br />';
echo pp($f);
echo '</pre>';
echo '</div>';

echo '</div>';