<?php

$this->extend('layouts/admin/default');

$label = ($this->item['id'] ? 'Редактиране' : 'Добавяне');

$this->section('title', $label);

$this->hookToMenu('main', 'control.groups', $label);

$this->section('styles', '<link href="assets/js/jstree/themes/default/style.min.css" rel="stylesheet" type="text/css" />');
$this->section('scripts', '<script src="assets/js/jstree/jstree.min.js"></script>');

?>

<h1><?php echo $label; ?></h1>

<form class="form-horizontal" action="<?php echo route(); ?>" method="post" enctype="multipart/form-data">
    <div style="margin-bottom: 20px">
        <?php echo $this->form->btnSave; ?>
        <?php echo $this->form->btnApply; ?>
        <?php echo $this->form->btnBack; ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->form->name->renderLabel(); ?>
                            <?php echo $this->form->name; ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->form->alias->renderLabel(); ?>
                            <?php echo $this->form->alias; ?>
                        </div>
                    </div>
                    <div class="form-group" style="margin-bottom: 0">
                        <div class="col-md-12">
                            <div id="jstree"></div>
                            <input type="hidden" name="rights" value="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <?php echo $this->form->btnSave; ?>
        <?php echo $this->form->btnApply; ?>
        <?php echo $this->form->btnBack; ?>
    </div>
</form>
<?php $this->start('scripts'); ?>
<script>
$(function () {
	$('#jstree').jstree({
		'plugins' : ['checkbox', 'wholerow'],
		'checkbox' : {
		    /*'keep_selected_style' : false*/
	    },
		'core' : {
		    'data' : <?php echo json_encode(isset($this->tree) ? $this->tree : []); ?>,
		    'expand_selected_onload' : false
		}
	});
	$('input[name="btnSave"], input[name="btnApply"]').on('click', function () {
		$('input[name="rights"]').val(JSON.stringify($('#jstree').jstree().get_bottom_selected()));
	});
});
</script>
<?php $this->stop(); ?>